<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE employees [
<!ELEMENT employees (employee*)>
<!ELEMENT employee (name, phones, addresses, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (work|mobile) #REQUIRED>
<!ELEMENT addresses (address+)>
<!ELEMENT address (street, building_number, region, city, country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT building_number (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>


<employees>
    <employee>
        <name>John Doe</name>
        <phones>
            <phone type="work">123-456-7890</phone>
            <phone type="mobile">987-654-3210</phone>
        </phones>
        <addresses>
            <address>
                <street>Main Street</street>
                <building_number>123</building_number>
                <region>North</region>
                <city>Cityville</city>
                <country>Countryland</country>
            </address>
        </addresses>
        <email>john.doe@example.com</email>
    </employee>
    <employee>
        <name>John Doe</name>
        <phones>
            <phone type="work">123-456-7890</phone>
            <phone type="mobile">987-654-3210</phone>
        </phones>
        <addresses>
            <address>
                <street>Main Street</street>
                <building_number>123</building_number>
                <region>North</region>
                <city>Cityville</city>
                <country>Countryland</country>
            </address>
        </addresses>
        <email>john.doe@example.com</email>
    </employee>
    <employee>
        <name>Jane Smith</name>
        <phones>
            <phone type="home">111-222-3333</phone>
        </phones>
        <addresses>
            <address>
                <street>First Avenue</street>
                <building_number>456</building_number>
                <region>South</region>
                <city>Townsville</city>
                <country>Countryland</country>
            </address>
            <address>
                <street>Second Street</street>
                <building_number>789</building_number>
                <region>East</region>
                <city>Villageton</city>
                <country>Countryland</country>
            </address>
        </addresses>
        <email>jane.smith@example.com</email>
    </employee>
</employees>